import {
    Controller,
    Get,
    Post,
    Body,
    Param,
    UseGuards,
    HttpCode,
    Query,
    Patch,
} from '@nestjs/common';
import { ApiTags, ApiBearerAuth, ApiOperation, ApiResponse, ApiParam, ApiQuery, ApiBody } from '@nestjs/swagger';
import { AdminService } from './admin.service';
import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard';
import { RolesGuard } from '../../common/guards/roles.guard';
import { Roles } from '../../common/decorators/roles.decorator';
import { CurrentUser } from '../../common/decorators/current-user.decorator';

@ApiTags('admin')
@Controller('admin')
@UseGuards(JwtAuthGuard, RolesGuard)
@Roles('admin')
@ApiBearerAuth()
export class AdminController {
    constructor(private readonly adminService: AdminService) { }

    @Get('submissions')
    @ApiOperation({ summary: 'List pending place submissions' })
    @ApiResponse({ status: 200, description: 'Array of pending place submissions.' })
    @ApiResponse({ status: 401, description: 'Not authenticated.' })
    @ApiResponse({ status: 403, description: 'Forbidden — admin role required.' })
    async getPendingSubmissions() {
        return this.adminService.getPendingSubmissions();
    }

    @Post('submissions/:id/approve')
    @HttpCode(200)
    @ApiOperation({ summary: 'Approve a place submission' })
    @ApiParam({ name: 'id', description: 'Submission UUID' })
    @ApiResponse({ status: 200, description: 'Submission approved and place published.' })
    @ApiResponse({ status: 401, description: 'Not authenticated.' })
    @ApiResponse({ status: 403, description: 'Forbidden — admin role required.' })
    @ApiResponse({ status: 404, description: 'Submission not found.' })
    async approveSubmission(@Param('id') id: string, @CurrentUser() admin: any) {
        return this.adminService.approveSubmission(id, admin.id);
    }

    @Post('submissions/:id/reject')
    @HttpCode(200)
    @ApiOperation({ summary: 'Reject a place submission' })
    @ApiParam({ name: 'id', description: 'Submission UUID' })
    @ApiBody({ schema: { type: 'object', properties: { reason: { type: 'string' } } } })
    @ApiResponse({ status: 200, description: 'Submission rejected.' })
    @ApiResponse({ status: 401, description: 'Not authenticated.' })
    @ApiResponse({ status: 403, description: 'Forbidden — admin role required.' })
    @ApiResponse({ status: 404, description: 'Submission not found.' })
    async rejectSubmission(
        @Param('id') id: string,
        @Body('reason') reason: string,
        @CurrentUser() admin: any,
    ) {
        return this.adminService.rejectSubmission(id, admin.id, reason);
    }

    @Get('claims')
    @ApiOperation({ summary: 'List pending business claims' })
    @ApiResponse({ status: 200, description: 'Array of pending business claims.' })
    @ApiResponse({ status: 401, description: 'Not authenticated.' })
    @ApiResponse({ status: 403, description: 'Forbidden — admin role required.' })
    async getPendingClaims() {
        return this.adminService.getPendingClaims();
    }

    @Get('stats')
    @ApiOperation({ summary: 'Get dashboard statistics' })
    @ApiResponse({ status: 200, description: 'Dashboard stats: users, places, checkins, etc.' })
    @ApiResponse({ status: 401, description: 'Not authenticated.' })
    @ApiResponse({ status: 403, description: 'Forbidden — admin role required.' })
    async getStats() {
        return this.adminService.getDashboardStats();
    }

    @Post('generate-description')
    @HttpCode(200)
    @ApiOperation({ summary: 'Generate AI description for a place' })
    @ApiBody({
        schema: {
            type: 'object',
            required: ['name', 'district', 'category'],
            properties: {
                name: { type: 'string' },
                district: { type: 'string' },
                category: { type: 'string' },
                keywords: { type: 'array', items: { type: 'string' } },
            },
        },
    })
    @ApiResponse({ status: 200, description: 'Returns { description } generated by AI.' })
    @ApiResponse({ status: 401, description: 'Not authenticated.' })
    @ApiResponse({ status: 403, description: 'Forbidden — admin role required.' })
    async generateDescription(@Body() body: { name: string; district: string; category: string; keywords: string[] }) {
        return {
            description: await this.adminService.generateAiDescription(
                body.name,
                body.district,
                body.category,
                body.keywords || []
            )
        };
    }

    @Post('claims/:id/verify')
    @HttpCode(200)
    @ApiOperation({ summary: 'Verify a business claim' })
    @ApiParam({ name: 'id', description: 'Claim UUID' })
    @ApiResponse({ status: 200, description: 'Claim verified and place ownership assigned.' })
    @ApiResponse({ status: 401, description: 'Not authenticated.' })
    @ApiResponse({ status: 403, description: 'Forbidden — admin role required.' })
    @ApiResponse({ status: 404, description: 'Claim not found.' })
    async verifyClaim(@Param('id') id: string, @CurrentUser() admin: any) {
        return this.adminService.verifyClaim(id, admin.id);
    }

    // --- Users ---

    @Get('users')
    @ApiOperation({ summary: 'List users with pagination and search' })
    @ApiQuery({ name: 'page', required: false, type: Number, example: 1 })
    @ApiQuery({ name: 'limit', required: false, type: Number, example: 10 })
    @ApiQuery({ name: 'search', required: false, type: String, description: 'Filter by name or email' })
    @ApiResponse({ status: 200, description: 'Paginated list of users.' })
    @ApiResponse({ status: 401, description: 'Not authenticated.' })
    @ApiResponse({ status: 403, description: 'Forbidden — admin role required.' })
    async getUsers(
        @Query('page') page: number = 1,
        @Query('limit') limit: number = 10,
        @Query('search') search?: string,
    ) {
        return this.adminService.getUsers(Number(page), Number(limit), search);
    }

    @Post('users')
    @ApiOperation({ summary: 'Create a new user (admin)' })
    @ApiResponse({ status: 201, description: 'User created.' })
    @ApiResponse({ status: 400, description: 'Validation error.' })
    @ApiResponse({ status: 401, description: 'Not authenticated.' })
    @ApiResponse({ status: 403, description: 'Forbidden — admin role required.' })
    async createUser(@Body() createUserDto: any) {
        return this.adminService.createUser(createUserDto);
    }

    @Patch('users/:id/ban')
    @ApiOperation({ summary: 'Ban a user' })
    @ApiParam({ name: 'id', description: 'User UUID' })
    @ApiResponse({ status: 200, description: 'User banned.' })
    @ApiResponse({ status: 401, description: 'Not authenticated.' })
    @ApiResponse({ status: 403, description: 'Forbidden — admin role required.' })
    @ApiResponse({ status: 404, description: 'User not found.' })
    async banUser(@Param('id') id: string) {
        return this.adminService.banUser(id);
    }

    @Patch('users/:id/activate')
    @ApiOperation({ summary: 'Activate a user' })
    @ApiParam({ name: 'id', description: 'User UUID' })
    @ApiResponse({ status: 200, description: 'User activated.' })
    @ApiResponse({ status: 401, description: 'Not authenticated.' })
    @ApiResponse({ status: 403, description: 'Forbidden — admin role required.' })
    @ApiResponse({ status: 404, description: 'User not found.' })
    async activateUser(@Param('id') id: string) {
        return this.adminService.activateUser(id);
    }
}
